### ISSUE TITLE
organize files into folder doesnt work with files that have illegal chars in filename

### ISSUE THREAD

**Issue by Masamune3210** [giwty/switch-backup-manager#9]
Perhaps replace illegal folder chars with a different char like a space or a -?

**Comment by giwty** [comment]
Wasn't sure if anyone will actually use it... thanks for trying :)
i need to fix the regex, will push a fix latter today

**Comment by Masamune3210** [comment]
I'm currently working on compiling all the dlc and the latest updates for the entire switch library, and I'm doing it in batches, so it makes it a whole lot easier. The only thing other than this that would help this much is ability to detect included dlc's in a nsp/nsz!

**Comment by Masamune3210** [comment]
Sorry to bug, but did you ever get to that fix?

**Comment by giwty** [comment]
Yes, i have it fixed locally, but waiting to complete another major feature, and will push it all once i'm done.
Hopefully wont take more then couple of days, think it will be worth the wait.
Thanks.

**Comment by Masamune3210** [comment]
Dont worry lol, didnt mean to sound impatient, just remembered that the issue existed and wanted to make sure everything was good

**Comment by giwty** [comment]
fixed.
